FROM nvidia/cuda:11.2.1-devel-ubuntu18.04

# Install system dependencies
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        curl \
        git \
    && apt-get clean

# Install python + requirements
RUN apt-get -y install python3
RUN apt-get -y install python3-pip
RUN python3 -m pip3 install -r requirements.txt

# Clone deep image prior repository
RUN git clone https://github.com/NimrodShabtay/deep-image-prior.git
WORKDIR /deep-image-prior

# Run script
CMD [ "python3", "./denoising.py"]
